### ISSUE TITLE
Re-initialization of GPU tensorflow and high VRAM usage

### ISSUE THREAD

**Issue by xander-m2k** [dronefreak/human-action-classification#14] opened 2021-02-10 13:27 UTC
Hi,

How can I solve the issue that every time a new image is processed, a new Tensorflow device is made?
Also, I have a GTX 1070 with 8GB VRAM, and the VRAM is fully used by this script, any idea why this is?

Xander

**Comment by dronefreak** [comment] 2021-02-13 10:00
Hi @xander-m2k 

Apologies for the late reply. This is actually a bug that I need to solve, just did not have the time yet. All the three different functions (pose, scene etc.) are called in separate TF sessions, which is the cause of this issue, it can be resolved by combining the three aspects of this project into a single TF session. Also, for your second question, `tf.config.allow_memory_growth` param might help. That is used to control the amount of memory utilized on the GPU. Hope this helps!

**Comment by xander-m2k** [comment] 2021-02-13 10:04
I was thinking that the code maybe contains a memory leak, I tested several similar repo's and rarely ended up with my VRAM fully stacked. Nevertheless, I will try to use that parameter and look if it helps.

**Closed as completed** 2021-09-22 08:39 UTC
